name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  python-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e scripts[dev]
      - name: Run pytest
        run: |
          cd scripts
          PYTHONPATH=src pytest

  node-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd server
          npm install
      - name: Type-check
        run: |
          cd server
          npm run build
      - name: Run unit tests
        run: |
          cd server
          npm run test -- --run
